version: "3.8"

services:
  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./back:/app
  
  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - node_modules:/front/node_modules
    command: sh -c "npm run dev"
  
volumes:
  node_modules:
